spring:
  application:
    name: agendamentodetransacoes

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /doc.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    
server:
  port: ${SERVER_PORT:8080}
  http2:
    enabled: true
  servlet:
    context-path: /api
